from pathlib import Path

import numpy as np
import pyvista as pv
from scipy.spatial import ConvexHull, Delaunay, cKDTree
from vtkmodules.util.numpy_support import vtk_to_numpy
from vtkmodules.vtkCommonCore import vtkIdList, vtkPoints
from vtkmodules.vtkCommonDataModel import vtkStaticCellLocator

from oamc.core import CompositeModel
from slicer.SlicedObject import SlicedObject


class _RayCaster:
    """
    Segment/mesh intersection tester that builds its spatial locator ONCE.

    `PolyData.ray_trace` may rebuild a locator on every call depending on
    the PyVista version, which is prohibitive when it is called once per
    node/face/ray. This helper keeps a single vtkStaticCellLocator.
    """

    def __init__(self, surface: pv.PolyData):
        self._surface = surface  # keep a reference: the locator does not own it
        self._locator = vtkStaticCellLocator()
        self._locator.SetDataSet(surface)
        self._locator.BuildLocator()
        self._tol = float(np.finfo(np.float32).eps)

    def hits(self, start, end) -> np.ndarray:
        """All intersection points of the segment [start, end] with the mesh, shape (n, 3)."""
        points = vtkPoints()
        points.SetDataTypeToDouble()
        cell_ids = vtkIdList()
        self._locator.IntersectWithLine(
            [float(c) for c in start], [float(c) for c in end], self._tol, points, cell_ids
        )
        if points.GetNumberOfPoints() == 0:
            return np.empty((0, 3))
        return vtk_to_numpy(points.GetData())


class SlicedMold(SlicedObject):
    """
    A sliced layer of the printed support/mold structure.

    Support layers are generated by building a "shadow volume" underneath
    the overhanging regions of the part and slicing it into printing
    layers. Unlike SlicedPiece, an approach/leave move's local normal is
    taken from the part's own outer surface (what the support is printed
    against), not from the support layer surface itself, so
    get_local_normals is overridden accordingly.

    Performance notes
    -----------------
    - The part's cell normals are computed once and shared by all the
      layers produced by slice_shadow_volume.
    - Ray casting uses a single locator (see _RayCaster) and only the
      rays that survive cheap vectorized filters are actually cast.
    - Slicing planes are cut in a single pass per direction.
    - Infill crossing detection is vectorized.
    """

    def __init__(
        self,
        surface: pv.PolyData,
        part_surface: pv.PolyData,
        q: int,
        z: float,
        contour_shells: list[np.ndarray] | None = None,
        infill_x: list[np.ndarray] | None = None,
        infill_y: list[np.ndarray] | None = None,
        infill_levels_x: np.ndarray | None = None,
        infill_levels_y: np.ndarray | None = None,
    ):
        super().__init__(surface)
        self.part_surface = part_surface  # goes through the setter below
        self.q = q
        self.z = z
        self.contour_shells = contour_shells or []
        self.infill_x = infill_x or []
        self.infill_y = infill_y or []
        # Fixed infill plane positions, computed once from layer zero and
        # shared by every layer so the infill paths stack vertically.
        self.infill_levels_x = infill_levels_x
        self.infill_levels_y = infill_levels_y

    # ------------------------------------------------------------------
    # Local normal override
    # ------------------------------------------------------------------

    @property
    def part_surface(self) -> pv.PolyData:
        return self._part_surface

    @part_surface.setter
    def part_surface(self, value: pv.PolyData) -> None:
        self._part_surface = value
        self._part_normals_cache = None

    @staticmethod
    def _unit_cell_normals(surface: pv.PolyData) -> np.ndarray:
        """Unit cell normals of a surface as a float64 array."""
        normals = np.array(surface.cell_normals, dtype=float)
        norms = np.linalg.norm(normals, axis=1, keepdims=True)
        norms[norms < 1e-12] = 1.0
        return normals / norms

    @property
    def _part_cell_normals(self) -> np.ndarray:
        """
        Cell normals of the part surface, computed once and cached
        (PyVista recomputes them on every access if the mesh does not
        store a normals array).
        """
        if self._part_normals_cache is None:
            self._part_normals_cache = self._unit_cell_normals(self.part_surface)
        return self._part_normals_cache

    def get_local_normals(self, points: np.ndarray) -> np.ndarray:
        """
        Support approach/leave moves are perpendicular to the part's own
        outer surface (what the support is printed against), not to the
        support layer surface itself.

        Batched version: one closest-cell query for all `points`
        (shape (n, 3)). The base class get_local_normal and the batched
        path helpers all go through this method.
        """
        points = np.atleast_2d(np.asarray(points, dtype=float))
        cell_ids = np.atleast_1d(self.part_surface.find_closest_cell(points))
        return self._part_cell_normals[cell_ids]

    # ------------------------------------------------------------------
    # Model-level utilities (pre-slicing)
    # ------------------------------------------------------------------

    @staticmethod
    def rotate_model(model: CompositeModel, rot_mat: np.ndarray) -> None:
        """Rotate the model's mesh nodes in place by the given rotation matrix."""
        model.mesh.nodes[:] = (rot_mat @ model.mesh.nodes.T).T
        model.mold.nodes[:] = (rot_mat @ model.mold.nodes.T).T
        object.__setattr__(model.mold, 'tree', cKDTree(model.mold.nodes))

        new_polydata = model.mold.polydata.copy()
        new_polydata.points = (rot_mat @ model.mold.polydata.points.T).T
        object.__setattr__(model.mold, 'polydata', new_polydata)

    @staticmethod
    def lift_model(model: CompositeModel, offset: float) -> None:
        """Translate the model's mesh nodes along Z by `offset`, in place."""
        model.mesh.nodes[:, 2] += offset
        model.mold.nodes[:, 2] += offset
        object.__setattr__(model.mold, 'tree', cKDTree(model.mold.nodes))

        new_polydata = model.mold.polydata.copy()
        new_polydata.points = model.mold.polydata.points.copy()
        new_polydata.points[:, 2] += offset
        object.__setattr__(model.mold, 'polydata', new_polydata)

    @staticmethod
    def solid_mesh_to_pyvista(solid_mesh) -> pv.UnstructuredGrid:
        """
        Convert a SolidMesh into a pv.UnstructuredGrid, automatically
        detecting each element's cell type from its node count.
        """
        nodes = solid_mesh.nodes
        connectivity = solid_mesh.connectivity
        n_elem, n_per_elem = connectivity.shape

        type_map = {
            4: pv.CellType.TETRA,
            8: pv.CellType.HEXAHEDRON,
            10: pv.CellType.QUADRATIC_TETRA,
            20: pv.CellType.QUADRATIC_HEXAHEDRON,
        }

        if n_per_elem not in type_map:
            raise ValueError(f"Unsupported element type: {n_per_elem} nodes")

        cell_type = type_map[n_per_elem]
        cells = np.hstack([
            np.full((n_elem, 1), n_per_elem, dtype=np.int64),
            connectivity.astype(np.int64)
        ]).ravel()
        cell_types = np.full(n_elem, cell_type, dtype=np.uint8)

        return pv.UnstructuredGrid(cells, cell_types, nodes)

    # ------------------------------------------------------------------
    # Shadow volume construction
    # ------------------------------------------------------------------

    @classmethod
    def _outer_surface(cls, model: CompositeModel, point_normals: bool = False) -> pv.PolyData:
        """
        Triangulated, linearized outer surface of the model's solid mesh,
        with cell normals (and optionally point normals). Shared by the
        three shadow-volume builders.
        """
        pv_mesh = cls.solid_mesh_to_pyvista(model.mesh)
        linear_mesh = pv_mesh.linear_copy()
        surface = linear_mesh.extract_surface(algorithm='dataset_surface')
        surface = surface.clean(tolerance=1e-6)
        surface = surface.triangulate()
        surface.compute_normals(cell_normals=True, point_normals=point_normals, inplace=True)
        return surface

    @staticmethod
    def _wedge_volume(
        top_pts: np.ndarray,
        bottom_pts: np.ndarray,
        triangles: np.ndarray,
    ) -> pv.UnstructuredGrid:
        """
        Build a volume of prisms (VTK wedges) between two point sheets.
        `triangles` index into top_pts; the same index + n_pts addresses
        the matching point of bottom_pts.
        """
        n_pts = len(top_pts)
        all_pts = np.vstack([top_pts, bottom_pts])  # bottom indexed from n_pts

        triangles = np.asarray(triangles, dtype=np.int64)
        n_tri = len(triangles)

        # Wedge = 6 nodes: top face (a, b, c), bottom face (a2, b2, c2)
        cells = np.hstack([
            np.full((n_tri, 1), 6, dtype=np.int64),
            triangles,
            triangles + n_pts,
        ]).ravel()
        cell_types = np.full(n_tri, pv.CellType.WEDGE, dtype=np.uint8)

        shadow = pv.UnstructuredGrid(cells, cell_types, all_pts)
        return shadow.clean(tolerance=1e-6)

    @classmethod
    def get_shadow_volume(cls, model: CompositeModel, plane_z: float = 0.0) -> pv.UnstructuredGrid:
        """
        Volume between the model's lower surface and the plane Z = plane_z.
        Each point of the lower surface is projected individually onto the
        plane (a variable "skirt" shape, not a uniform extrusion).
        """
        surface = cls._outer_surface(model, point_normals=False)

        # Downward-facing faces
        normals = surface.cell_data["Normals"]
        downward_mask = normals[:, 2] < 0
        n_down = downward_mask.sum()
        print(f"Downward-facing faces: {n_down} / {surface.n_cells}")

        if n_down == 0:
            raise ValueError(
                "No downward-facing face found - check that rotate_model() "
                "was applied before get_shadow_volume()"
            )

        bottom = surface.extract_cells(np.where(downward_mask)[0])
        bottom = bottom.extract_surface(algorithm='dataset_surface')
        bottom = bottom.triangulate()

        # Individually project each point of the lower surface onto the plane
        pts_top = bottom.points.copy()
        pts_bot = pts_top.copy()
        pts_bot[:, 2] = plane_z

        faces = bottom.faces.reshape(-1, 4)[:, 1:]  # triangles (n_tri, 3)
        shadow = cls._wedge_volume(pts_top, pts_bot, faces)

        print(f"Shadow volume: {shadow.volume:.3f} mm3")

        return shadow

    @classmethod
    def get_shadow_volume_cone(
        cls,
        model: CompositeModel,
        plane_z: float = 0.0,
        node_tol: float = 1.0,
        tri_tol: float = 1.0,
        offset_faces: float = 0.1,
        cone_angle: float = 30.0,
        no_rays: int = 8,
        start_phase: float = 0.0,
        distance_from_contour: float = 0.5,
    ) -> pv.UnstructuredGrid:
        """
        Compute the shadow volume using a cone of rays cast from the
        part's lower-surface faces.

        Parameters
        ----------
        node_tol             : max distance from a node to the outer surface
        tri_tol               : max distance from a centroid to the outer surface
        offset_faces          : offset of the centroid along the normal before
                                 casting rays (avoids self-intersection)
        cone_angle             : half-angle of the ray cone (degrees)
        no_rays               : number of rays in the cone (excluding the central ray)
        start_phase            : rotation of the cone around Z (degrees)
        distance_from_contour  : min distance from the projected centroid to the
                                  shadow contour to be included

        Performance: every test that does not need a ray cast (plane hit
        inside the bounds, distance to the shadow contour...) is evaluated
        for all faces at once; only the surviving (face, ray) pairs are
        actually cast, against a single locator.
        """
        # 1. Linearized outer surface
        surface = cls._outer_surface(model, point_normals=True)

        pts = surface.points
        normals = surface.cell_data["Normals"]
        faces = surface.faces.reshape(-1, 4)[:, 1:]  # (n_tri, 3)

        # 2. Pre-filter candidate triangles (outer surface, facing down)
        candidate_ids = np.where(normals[:, 2] < 0)[0]
        print(f"Candidate triangles (downward-facing normals): {len(candidate_ids)}")

        # 3. Shadow contour = convex hull of the XY projection of the surface
        pts_2d = pts[:, :2]

        print(f"Surface points: {len(pts_2d)}, X:[{pts_2d[:,0].min():.1f},{pts_2d[:,0].max():.1f}] Y:[{pts_2d[:,1].min():.1f},{pts_2d[:,1].max():.1f}]")

        hull = ConvexHull(pts_2d)
        hull_pts_2d = pts_2d[hull.vertices]
        boundary_tree = cKDTree(hull_pts_2d)

        print(f"Shadow contour (convex hull): {len(hull_pts_2d)} points")

        x_min, x_max = pts_2d[:, 0].min(), pts_2d[:, 0].max()
        y_min, y_max = pts_2d[:, 1].min(), pts_2d[:, 1].max()

        # 4. Ray cone: one central vertical ray + no_rays tilted rays
        cone_angle_rad = np.deg2rad(cone_angle)
        phis = np.deg2rad(start_phase) + 2 * np.pi * np.arange(no_rays) / no_rays
        cone_directions = np.vstack([
            [0.0, 0.0, -1.0],
            np.column_stack([
                np.sin(cone_angle_rad) * np.cos(phis),
                np.sin(cone_angle_rad) * np.sin(phis),
                np.full(no_rays, -np.cos(cone_angle_rad)),
            ]),
        ])

        ray_length = (pts[:, 2].max() - plane_z) * 2.0  # long enough to cross through

        # 5. Face-level vectorized setup
        centroids = pts[faces[candidate_ids]].mean(axis=1)           # (n, 3)
        origins = centroids + offset_faces * normals[candidate_ids]  # (n, 3)

        # Faces too close to the shadow contour are discarded
        dist_c, _ = boundary_tree.query(centroids[:, :2], workers=-1)
        keep = ~(dist_c < distance_from_contour)
        face_ids = candidate_ids[keep]
        origins = origins[keep]

        n_faces, n_dirs = len(face_ids), len(cone_directions)
        free = np.zeros((n_faces, n_dirs), dtype=bool)
        plane_hits = np.zeros((n_faces, n_dirs, 3))

        # 6. For each direction: cheap vectorized filters, then ray casts
        caster = _RayCaster(surface)

        for r, ray_dir in enumerate(cone_directions):
            if ray_dir[2] >= 0:
                continue  # ray pointing upward

            t = (plane_z - origins[:, 2]) / ray_dir[2]
            hit = origins + t[:, None] * ray_dir
            plane_hits[:, r] = hit

            candidates = np.flatnonzero(
                (hit[:, 0] >= x_min) & (hit[:, 0] <= x_max)
                & (hit[:, 1] >= y_min) & (hit[:, 1] <= y_max)
            )
            if len(candidates) == 0:
                continue

            dist_hit, _ = boundary_tree.query(hit[candidates, :2], workers=-1)
            candidates = candidates[dist_hit > distance_from_contour]

            for i in candidates:
                end = origins[i] + ray_length * ray_dir
                if len(caster.hits(origins[i], end)) == 0:  # ray not blocked
                    free[i, r] = True

        # Same output order as a face-by-face, ray-by-ray loop
        face_idx, ray_idx = np.nonzero(free)
        n_roof_faces = int(free.any(axis=1).sum())
        print(f"Roof faces: {n_roof_faces}, free ray pairs: {len(face_idx)}")

        # 7. Build the volume from the ray pairs
        if len(face_idx) == 0:
            raise ValueError("No free ray found - adjust the cone parameters")

        top_pts = origins[face_idx]                 # points on the part
        bottom_pts = plane_hits[face_idx, ray_idx]  # points on the plane (follow the ray, not vertical)

        # 2D Delaunay on the XY projections of top_pts to get a consistent surface
        triangles = Delaunay(top_pts[:, :2]).simplices
        shadow_volume = cls._wedge_volume(top_pts, bottom_pts, triangles)

        print(f"Z range: [{shadow_volume.points[:,2].min():.3f}, "
            f"{shadow_volume.points[:,2].max():.3f}] - plane_z={plane_z}")
        print(f"Volume: {shadow_volume.volume:.3f} mm3")

        return shadow_volume

    @classmethod
    def get_shadow_volume_vertical(
        cls,
        model: CompositeModel,
        plane_z: float = 0.0,
        offset_faces: float = 0.1,
    ) -> tuple[pv.UnstructuredGrid, pv.PolyData, pv.PolyData]:
        """
        Build the support volume by vertical projection from each node of
        the lower surface:
        - if the node -> plane segment does not cross the part: direct
          projection onto plane_z
        - if the segment crosses the part: take the first intersection as
          the lower point (volume between the node and the first
          intersection)

        Performance: a single ray-casting locator is built for the upward
        surface, and rays that cannot touch it (outside its bounding box)
        are skipped without being cast.
        """
        surface = cls._outer_surface(model, point_normals=True)

        pts = surface.points
        normals = surface.cell_data["Normals"]
        point_normals = surface.point_data["Normals"]
        faces = surface.faces.reshape(-1, 4)[:, 1:]

        # Nodes on the lower surface (normal with negative Z component)
        candidate_ids = np.where(normals[:, 2] < 0)[0]
        candidate_faces = faces[candidate_ids]
        # np.unique: sorted unique nodes + index of each face vertex in that list
        candidate_nodes, inverse = np.unique(candidate_faces.ravel(), return_inverse=True)
        face_node_idx = inverse.reshape(-1, 3)  # triangles indexing top_pts

        print(f"Candidate nodes: {len(candidate_nodes)}")

        # "Upward-facing" surface used for the intersection tests
        upward_ids = np.where(normals[:, 2] > 0)[0]
        upward_surface = surface.extract_cells(upward_ids)
        upward_surface = upward_surface.extract_surface(algorithm='dataset_surface')
        upward_surface = upward_surface.triangulate()

        print(f"Upward-facing faces: {len(upward_ids)} / {surface.n_cells}")

        caster = _RayCaster(upward_surface)
        ux_min, ux_max, uy_min, uy_max, uz_min, uz_max = upward_surface.bounds
        eps = 1e-6

        # ---- Per-node bottom points ---------------------------------------
        top_pts = pts[candidate_nodes]
        origins = top_pts + offset_faces * point_normals[candidate_nodes]

        # Default: direct projection onto the plane
        bottom_pts = top_pts.astype(float).copy()
        bottom_pts[:, 2] = plane_z

        # A vertical ray can only hit the upward surface inside its bounds
        may_hit = (
            (origins[:, 0] >= ux_min - eps) & (origins[:, 0] <= ux_max + eps)
            & (origins[:, 1] >= uy_min - eps) & (origins[:, 1] <= uy_max + eps)
            & (origins[:, 2] >= uz_min - eps) & (plane_z - 1.0 <= uz_max + eps)
        )

        for i in np.flatnonzero(may_hit):
            origin = origins[i]
            end = np.array([origin[0], origin[1], plane_z - 1.0])

            hits = caster.hits(origin, end)
            if len(hits) == 0:
                continue

            # The ray goes straight down: the first hit is the highest one
            first_hit = hits[np.argmax(hits[:, 2])]
            if first_hit[2] > plane_z:
                bottom_pts[i] = first_hit  # volume down to the intersection

        print(f"Top/bottom pairs: {len(top_pts)}")

        print(f"top_pts XY range: X[{top_pts[:,0].min():.2f}, {top_pts[:,0].max():.2f}] "
            f"Y[{top_pts[:,1].min():.2f}, {top_pts[:,1].max():.2f}]")

        # Just for visualizing the distribution of top_pts and bottom_pts
        cloud_top = pv.PolyData(np.array(top_pts))
        cloud_bot = pv.PolyData(bottom_pts)

        # ---- Maximum XY distance for a valid intersection --------------------
        tri_pts = pts[candidate_faces]  # (n_tri, 3, 3)
        edges = tri_pts - np.roll(tri_pts, -1, axis=1)
        max_xy_dist = np.linalg.norm(edges, axis=2).mean() * 2.0
        print(f"max_xy_dist: {max_xy_dist:.3f} mm")

        # ---- Prism validity test ----------------------------------------------
        a, b, c = face_node_idx[:, 0], face_node_idx[:, 1], face_node_idx[:, 2]
        centroid_top = (top_pts[a] + top_pts[b] + top_pts[c]) / 3.0
        origin_test = centroid_top + np.array([0, 0, -offset_faces])
        end_test = (bottom_pts[a] + bottom_pts[b] + bottom_pts[c]) / 3.0

        z_lo = np.minimum(origin_test[:, 2], end_test[:, 2])
        z_hi = np.maximum(origin_test[:, 2], end_test[:, 2])

        # Only segments whose bounding box overlaps the upward surface can
        # produce an intersection
        seg_min = np.minimum(origin_test, end_test)
        seg_max = np.maximum(origin_test, end_test)
        overlaps = (
            (seg_max[:, 0] >= ux_min - eps) & (seg_min[:, 0] <= ux_max + eps)
            & (seg_max[:, 1] >= uy_min - eps) & (seg_min[:, 1] <= uy_max + eps)
            & (seg_max[:, 2] >= uz_min - eps) & (seg_min[:, 2] <= uz_max + eps)
        )

        valid = np.ones(len(face_node_idx), dtype=bool)
        for k in np.flatnonzero(overlaps):
            hits = caster.hits(origin_test[k], end_test[k])
            if len(hits) == 0:
                continue

            # Keep only intersections truly between top and bottom and close in XY
            real = (
                (hits[:, 2] > z_lo[k]) & (hits[:, 2] < z_hi[k])
                & (np.linalg.norm(hits[:, :2] - origin_test[k, :2], axis=1) < max_xy_dist)
            )
            if real.any():
                valid[k] = False

        valid_triangles = face_node_idx[valid]
        if len(valid_triangles) == 0:
            raise ValueError("No valid prism - every triangle is blocked by the part")

        shadow = cls._wedge_volume(np.asarray(top_pts, dtype=float), bottom_pts, valid_triangles)

        print(f"Z range: [{shadow.points[:,2].min():.3f}, "
              f"{shadow.points[:,2].max():.3f}]")
        print(f"Volume: {shadow.volume:.3f} mm3")

        return shadow, cloud_top, cloud_bot

    @staticmethod
    def compute_shadow_contour(surface: pv.PolyData, plane_z: float, alpha: float = 5.0):
        """
        Compute the shadow contour (silhouette projected onto Z = plane_z)
        by working directly in 2D on the XY coordinates.
        """
        # Project every point onto Z = plane_z
        pts_2d = surface.points[:, :2].copy()  # keep XY only

        # Rebuild a flat 2D mesh to extract the boundary
        pts_3d_flat = np.column_stack([pts_2d, np.full(len(pts_2d), plane_z)])
        flat_surface = pv.PolyData(pts_3d_flat)

        # 2D Delaunay, forcing the projection axis
        shadow_2d = flat_surface.delaunay_2d(alpha=alpha, progress_bar=False)

        if shadow_2d.n_cells == 0:
            # Fallback: 2D convex hull via scipy
            hull = ConvexHull(pts_2d)
            hull_pts = pts_3d_flat[hull.vertices]
            # Close the polygon
            hull_pts = np.vstack([hull_pts, hull_pts[0]])
            boundary_pts_2d = hull_pts[:, :2]
            print("Warning: empty delaunay_2d -> falling back to 2D convex hull")
            return shadow_2d, boundary_pts_2d, cKDTree(boundary_pts_2d)

        # Extract the boundary
        boundary = shadow_2d.extract_feature_edges(
            boundary_edges=True,
            non_manifold_edges=False,
            feature_edges=False,
            manifold_edges=False,
        )

        if boundary.n_points == 0:
            raise ValueError("Empty shadow contour even after delaunay_2d - check alpha")

        boundary_pts_2d = boundary.points[:, :2]
        boundary_tree = cKDTree(boundary_pts_2d)

        print(f"Shadow contour: {len(boundary_pts_2d)} points")
        return shadow_2d, boundary_pts_2d, boundary_tree

    # ------------------------------------------------------------------
    # Legacy global slicing-plane infill (superseded by slice_shadow_volume,
    # kept for reference)
    # ------------------------------------------------------------------

    @staticmethod
    def generate_support_slicing_planes(
        shadow_volume: pv.UnstructuredGrid,
        infill_percentage: float = 20.0,
        plane_z: float = 0.0,
    ) -> tuple[list[dict], list[dict]]:
        """
        Generate two families of slicing planes (normal to X and normal to
        Y) for the fiber paths inside the support volume.

        The plane spacing is derived from the infill percentage:
        - 100% -> planes spaced one nozzle width apart (full infill)
        - 20%  -> planes spaced 5x the nozzle width apart

        Parameters
        ----------
        shadow_volume      : UnstructuredGrid of the support volume
        infill_percentage  : infill percentage (1-100)
        plane_z            : altitude of the printing plane

        Returns
        -------
        planes_x : list of {"origin", "normal"} dicts - planes normal to X
        planes_y : list of {"origin", "normal"} dicts - planes normal to Y
        """
        # 1. Extract the volume's surface to get the XY bounds
        surface = shadow_volume.extract_surface(algorithm='dataset_surface')
        bounds = surface.bounds
        # (xmin, xmax, ymin, ymax, zmin, zmax)
        x_min, x_max = bounds[0], bounds[1]
        y_min, y_max = bounds[2], bounds[3]
        z_min, z_max = bounds[4], bounds[5]

        print(f"Shadow volume bounds: "
              f"X[{x_min:.1f}, {x_max:.1f}] "
              f"Y[{y_min:.1f}, {y_max:.1f}] "
              f"Z[{z_min:.1f}, {z_max:.1f}]")

        # 2. Plane spacing from the infill percentage. For an XY grid:
        #    infill_pct = (nozzle_diameter / spacing)^2 * 100
        #    -> spacing = nozzle_diameter / sqrt(infill_pct / 100)
        nozzle_diameter = 0.70  # mm - matches the model's fiber_diameter

        spacing = SlicedMold.infill_spacing(nozzle_diameter, infill_percentage)

        print(f"Infill {infill_percentage}% -> plane spacing: {spacing:.3f} mm")

        orig = np.array([
            (x_min + x_max) / 2.0,
            (y_min + y_max) / 2.0,
            (z_min + z_max) / 2.0,
        ])

        # 3. Family 1: planes normal to X (YZ cuts)
        planes_x = [
            {"origin": np.array([x, orig[1], orig[2]]), "normal": np.array([1.0, 0.0, 0.0])}
            for x in np.arange(x_min, x_max + spacing, spacing)
        ]

        # 4. Family 2: planes normal to Y (XZ cuts)
        planes_y = [
            {"origin": np.array([orig[0], y, orig[2]]), "normal": np.array([0.0, 1.0, 0.0])}
            for y in np.arange(y_min, y_max + spacing, spacing)
        ]

        print(f"Planes generated: {len(planes_x)} normal to X, "
              f"{len(planes_y)} normal to Y")

        return planes_x, planes_y

    @staticmethod
    def infill_spacing(nozzle_diameter: float, infill_percentage: float) -> float:
        """Spacing of a two-direction grid (X + Y per layer, crossings counted once)
        giving the requested area/volume fraction."""
        ratio = np.clip(infill_percentage, 0.1, 100.0) / 100.0
        return nozzle_diameter / (1.0 - np.sqrt(1.0 - ratio))
    
    @staticmethod
    def generate_support_infill_lines(
        shadow_volume: pv.UnstructuredGrid,
        planes_x: list[dict],
        planes_y: list[dict],
    ) -> tuple[list[np.ndarray], list[np.ndarray]]:
        """
        Intersect the support volume with both plane families to generate
        the infill polylines.

        Returns
        -------
        infill_x : polylines from the planes normal to X
        infill_y : polylines from the planes normal to Y
        """
        surface = shadow_volume.extract_surface(algorithm='dataset_surface')
        surface = surface.triangulate()

        infill_x = []
        infill_y = []

        for plane in planes_x:
            cut = surface.slice(normal=plane["normal"], origin=plane["origin"])
            if cut.n_points > 0:
                infill_x.extend(SlicedObject.order_segments(cut))

        for plane in planes_y:
            cut = surface.slice(normal=plane["normal"], origin=plane["origin"])
            if cut.n_points > 0:
                infill_y.extend(SlicedObject.order_segments(cut))

        print(f"Polylines generated: {len(infill_x)} (X), {len(infill_y)} (Y)")

        return infill_x, infill_y

    # ------------------------------------------------------------------
    # Layer generation from the shadow volume
    # ------------------------------------------------------------------

    # @staticmethod
    # def compute_dist_to_part(
    #     shadow_volume: pv.UnstructuredGrid,
    #     part_surface: pv.PolyData,
    #     plane_z: float = 0.0,
    #     copy: bool = True,
    # ) -> pv.UnstructuredGrid:
    #     """
    #     Compute dist_to_part as the minimum of:
    #     - the distance to the part's surface
    #     - the distance to the printing plane Z = plane_z

    #     This way, inside a cavity, the distance is correctly computed from
    #     the nearest usable reference (the bottom plane or the part), not
    #     from the far side of the cavity.

    #     copy=False writes the field into `shadow_volume` itself instead of
    #     into a copy (saves a full copy of the volume when the caller
    #     already owns it).
    #     """
    #     tree = cKDTree(part_surface.points)
    #     vol_pts = shadow_volume.points

    #     # Distance to the part's surface (all cores)
    #     dist_to_part_surface, _ = tree.query(vol_pts, workers=-1)

    #     # Distance to the printing plane (pure vertical distance)
    #     dist_to_plane = np.abs(vol_pts[:, 2] - plane_z)

    #     distances = np.minimum(dist_to_part_surface, dist_to_plane)

    #     if copy:
    #         shadow_volume = shadow_volume.copy()
    #     shadow_volume["dist_to_part"] = distances

    #     print(f"dist_to_part: min={distances.min():.3f}, max={distances.max():.3f} mm")
    #     return shadow_volume

    @staticmethod
    def _chain_segments(cut: pv.PolyData) -> list[np.ndarray] | None:
        """
        Chain the 2-point line cells of `cut` into ordered polylines.

        vtkStripper leaves the output of a multi-level contour fragmented,
        so the (simple) chaining is done here. Returns None if the segment
        graph is not made of simple chains/loops (a point shared by more
        than two segments), so that the caller can fall back to a slower
        but more general method.
        """
        cut = cut.clean()  # merge coincident points
        lines = np.asarray(cut.lines)
        if lines.size == 0 or lines.size % 3 or not np.all(lines[::3] == 2):
            return None

        segs = lines.reshape(-1, 3)[:, 1:]
        n_pts = cut.n_points

        degree = np.bincount(segs.ravel(), minlength=n_pts)
        if degree.max() > 2:
            return None

        # Each point has at most two neighbours (-1 = none)
        neighbors = np.full((n_pts, 2), -1, dtype=np.int64)
        fill = np.zeros(n_pts, dtype=np.int64)
        for a, b in segs:
            neighbors[a, fill[a]] = b
            fill[a] += 1
            neighbors[b, fill[b]] = a
            fill[b] += 1

        visited = np.zeros(n_pts, dtype=bool)
        chains = []

        def walk(start):
            chain = [start]
            visited[start] = True
            prev, cur = -1, start
            while True:
                nxt = -1
                for cand in neighbors[cur]:
                    if cand != -1 and cand != prev and not visited[cand]:
                        nxt = cand
                        break
                if nxt == -1:
                    break
                chain.append(nxt)
                visited[nxt] = True
                prev, cur = cur, nxt
            return chain

        # Open chains first (start from their end points), then closed loops
        for start in np.flatnonzero(degree == 1):
            if not visited[start]:
                chains.append(walk(start))
        for start in np.flatnonzero((degree == 2) & ~visited):
            if not visited[start]:
                chain = walk(start)
                chain.append(chain[0])  # close the loop
                chains.append(chain)

        pts = cut.points
        return [pts[c] for c in chains if len(c) >= 2]

    @classmethod
    def _cut_axis_planes(
        cls,
        zone: pv.PolyData,
        axis: int,
        levels: np.ndarray,
    ) -> list[np.ndarray]:
        """
        Cut `zone` with all the planes {coordinate[axis] = level} in a
        single pass and return the polylines, grouped plane by plane
        (same order as one `slice` call per plane).

        The planes are level sets of one scalar field (the coordinate), so
        a single contour call replaces one full mesh traversal per plane.
        """
        levels = np.asarray(levels, dtype=float)
        if zone.n_points == 0 or len(levels) == 0:
            return []

        zone = zone.copy(deep=False)
        zone.point_data["_plane_coord"] = zone.points[:, axis]

        cut = zone.contour(isosurfaces=levels.tolist(), scalars="_plane_coord")
        if cut.n_points == 0:
            return []

        polylines = cls._chain_segments(cut)
        if polylines is None:
            # General fallback: one slice per plane
            normal = np.zeros(3)
            normal[axis] = 1.0
            polylines = []
            for level in levels:
                origin = np.zeros(3)
                origin[axis] = level
                piece = zone.slice(normal=normal, origin=origin)
                if piece.n_points > 0:
                    polylines.extend(cls.order_segments(piece))
            return polylines
        if not polylines:
            return []

        # Restore plane-by-plane order (all points of a polyline lie on one plane)
        offsets = np.array([poly[0, axis] for poly in polylines])
        plane_idx = np.abs(offsets[:, None] - levels[None, :]).argmin(axis=1)
        order = np.argsort(plane_idx, kind="stable")

        return [polylines[i] for i in order]

    @classmethod
    def slice_shadow_volume(
        cls,
        shadow_volume: pv.UnstructuredGrid,
        part_surface: pv.PolyData,
        layer_height: float = 0.35,
        nozzle_diameter: float = 0.70,
        n_contour_shells: int = 2,
        infill_percentage: float = 20.0,
        plane_z: float = 0.0,
    ) -> list["SlicedMold"]:
        """
        Slice the support (shadow) volume into a list of SlicedMold layers.

        The scalar field q = (Z - plane_z) / layer_height grows with
        altitude; each integer value of q corresponds to one printing
        layer. For every layer this computes:
        - the contour shells (isosurfaces of dist_to_part)
        - the XY grid infill
        """
        # 1. Scalar field q on the shadow volume (integer values at
        #    altitudes plane_z + n * layer_height)
        shadow = shadow_volume.copy()
        z_coords = shadow.points[:, 2]
        shadow["q"] = (z_coords - plane_z) / layer_height

        q_min = shadow["q"].min()
        q_max = shadow["q"].max()
        print(f"q range: [{q_min:.2f}, {q_max:.2f}] "
              f"-> {int(q_max - q_min) + 1} layers")

        # 2. dist_to_part (distance to the part + plane); `shadow` is
        #    already our own copy, so no second copy is needed.
        # shadow = cls.compute_dist_to_part(shadow, part_surface, plane_z=plane_z, copy=False)
        part_tri = part_surface.triangulate().clean()

        # Part normals: computed once, shared by every layer
        part_normals = cls._unit_cell_normals(part_surface)

        # Infill spacing
        spacing = SlicedMold.infill_spacing(nozzle_diameter, infill_percentage)

        # Integer q values corresponding to layers
        q_values = np.arange(
            int(np.ceil(q_min)),
            int(np.floor(q_max)) + 1,
            1
        )

        # Infill planes, generated ONCE from layer zero (the footprint of
        # the shadow volume on the printing plane) and reused for every
        # layer, so the infill paths stack exactly on top of each other
        # instead of shifting with the part's geometry.
        base_layer = shadow.contour(isosurfaces=[float(q_values[0])], scalars="q")
        if base_layer.n_points > 0:
            base_bounds = base_layer.bounds
        else:
            base_bounds = shadow.bounds
        infill_levels_x = np.arange(base_bounds[0], base_bounds[1] + spacing, spacing)
        infill_levels_y = np.arange(base_bounds[2], base_bounds[3] + spacing, spacing)
        print(f"Fixed infill planes: {len(infill_levels_x)} normal to X, "
              f"{len(infill_levels_y)} normal to Y (from layer q={q_values[0]})")

        shell_values = [(i + 0.5) * nozzle_diameter for i in range(n_contour_shells)]
        inner_offset = n_contour_shells * nozzle_diameter

        layers = []

        for q_val in q_values:
            z_layer = plane_z + q_val * layer_height
            print(f"Layer q={q_val}, Z={z_layer:.3f} mm")

            # 3. Isosurface q = q_val = the volume's "slice" at this altitude
            layer_surface = shadow.contour(
                isosurfaces=[float(q_val)],
                scalars="q"
            )

            if layer_surface.n_points == 0:
                print("  -> empty layer, skipped")
                continue

            layer_surface = layer_surface.triangulate()
            layer_surface.compute_normals(
                cell_normals=False, point_normals=True, inplace=True
            )

            # Interpolate dist_to_part onto this isosurface. (Do not rely on
            # the values carried by the contour filter itself: they differ
            # from the volume's own interpolation.)

            #layer_surface = layer_surface.sample(shadow)
            layer_surface = layer_surface.compute_implicit_distance(part_tri, inplace=False)
            d_part = np.abs(layer_surface["implicit_distance"])
            d_plane = np.full(layer_surface.n_points, z_layer - plane_z)   # constant sur une couche
            layer_surface["dist_to_part"] = np.minimum(d_part, d_plane)

            # 4. Contour shells: isolines of dist_to_part on this layer
            contour_shells = []
            for val in shell_values:
                iso = layer_surface.contour(
                    isosurfaces=[val],
                    scalars="dist_to_part"
                )
                if iso.n_points > 0:
                    stripped = iso.strip(join=True)
                    contour_shells.extend(cls.order_segments(stripped))

            # 5. Inner zone: clip the layer beyond the shells.
            # PyVista's clip_scalar convention is easy to get backwards:
            # invert=True keeps values BELOW value. To keep dist > inner_offset
            # (the actual inner zone, past the contour shells), invert must be False.
            inner_zone = layer_surface.clip_scalar(
                scalars="dist_to_part",
                value=inner_offset,
                invert=False  # keep dist > inner_offset
            )

            infill_x = []
            infill_y = []

            if inner_zone.n_points > 0:
                # Same fixed planes for every layer (see infill_levels_*
                # above): one pass per direction.
                infill_x = cls._cut_axis_planes(inner_zone, 0, infill_levels_x)
                infill_y = cls._cut_axis_planes(inner_zone, 1, infill_levels_y)

            print(f"  -> {len(contour_shells)} shells, "
                  f"{len(infill_x)} infill_x, {len(infill_y)} infill_y")

            layer = cls(
                surface=layer_surface,
                part_surface=part_surface,
                q=int(q_val),
                z=z_layer,
                contour_shells=contour_shells,
                infill_x=infill_x,
                infill_y=infill_y,
                infill_levels_x=infill_levels_x,
                infill_levels_y=infill_levels_y,
            )
            layer._part_normals_cache = part_normals  # shared, read-only
            layers.append(layer)

        return layers

    @classmethod
    def slice_model(
        cls,
        model: CompositeModel,
        part_surface: pv.PolyData,
        layer_height: float = 0.35,
        nozzle_diameter: float = 0.70,
        n_contour_shells: int = 2,
        infill_percentage: float = 20.0,
        plane_z: float = 0.0,
        offset_faces: float = 0.1,
    ) -> list["SlicedMold"]:
        """
        Convenience method: compute the model's shadow volume (vertical
        projection method) and slice it into SlicedMold layers in one call.
        """
        shadow_volume, _, _ = cls.get_shadow_volume_vertical(
            model,
            plane_z=plane_z,
            offset_faces=offset_faces,
        )

        return cls.slice_shadow_volume(
            shadow_volume,
            part_surface=part_surface,
            layer_height=layer_height,
            nozzle_diameter=nozzle_diameter,
            n_contour_shells=n_contour_shells,
            infill_percentage=infill_percentage,
            plane_z=plane_z,
        )

    # ------------------------------------------------------------------
    # Infill crossing cuts
    # ------------------------------------------------------------------

    @staticmethod
    def segment_intersection_2d(
        p1: np.ndarray, p2: np.ndarray,
        q1: np.ndarray, q2: np.ndarray,
        tol: float = 1e-6,
    ) -> np.ndarray | None:
        """
        2D (XY) intersection between segments [p1, p2] and [q1, q2].
        Returns the 3D point interpolated on [p1, p2], or None if there is
        no intersection.

        Scalar reference version; the cutting code below uses the
        vectorized _segment_intersections_2d.
        """
        d1 = p2[:2] - p1[:2]
        d2 = q2[:2] - q1[:2]

        cross = d1[0] * d2[1] - d1[1] * d2[0]
        if abs(cross) < tol:
            return None  # parallel

        delta = q1[:2] - p1[:2]
        t = (delta[0] * d2[1] - delta[1] * d2[0]) / cross
        u = (delta[0] * d1[1] - delta[1] * d1[0]) / cross

        if 0 <= t <= 1 and 0 <= u <= 1:
            hit_2d = p1[:2] + t * d1
            hit_z = p1[2] + t * (p2[2] - p1[2])  # also interpolate Z
            return np.array([hit_2d[0], hit_2d[1], hit_z])

        return None

    @staticmethod
    def _segment_intersections_2d(
        p1: np.ndarray, p2: np.ndarray,
        q1: np.ndarray, q2: np.ndarray,
        tol: float = 1e-6,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Vectorized XY intersection of N segment pairs ([p1, p2] x [q1, q2],
        each array of shape (N, 3)). Returns (hit_mask, t) where t is the
        parameter of the hit along [p1, p2].
        """
        d1 = p2[:, :2] - p1[:, :2]
        d2 = q2[:, :2] - q1[:, :2]

        cross = d1[:, 0] * d2[:, 1] - d1[:, 1] * d2[:, 0]
        delta = q1[:, :2] - p1[:, :2]

        with np.errstate(divide="ignore", invalid="ignore"):
            t = (delta[:, 0] * d2[:, 1] - delta[:, 1] * d2[:, 0]) / cross
            u = (delta[:, 0] * d1[:, 1] - delta[:, 1] * d1[:, 0]) / cross

        hit = (np.abs(cross) >= tol) & (t >= 0) & (t <= 1) & (u >= 0) & (u <= 1)
        return hit, t

    @staticmethod
    def interpolate_polyline_at(
        poly: np.ndarray,
        cum_lengths: np.ndarray,
        s: float,
    ) -> np.ndarray:
        """Interpolate a point on the polyline at curvilinear position s."""
        s = np.clip(s, 0, cum_lengths[-1])
        idx = np.searchsorted(cum_lengths, s, side='right') - 1
        idx = np.clip(idx, 0, len(poly) - 2)

        seg_len = cum_lengths[idx + 1] - cum_lengths[idx]
        if seg_len < 1e-12:
            return poly[idx]

        t = (s - cum_lengths[idx]) / seg_len
        return poly[idx] + t * (poly[idx + 1] - poly[idx])

    @classmethod
    def sample_polyline_between(
        cls,
        poly: np.ndarray,
        cum_lengths: np.ndarray,
        s_start: float,
        s_end: float,
    ) -> np.ndarray:
        """
        Extract the sub-segment of poly between curvilinear positions
        s_start and s_end, interpolating the exact cut points.
        """
        start_pt = cls.interpolate_polyline_at(poly, cum_lengths, s_start)
        end_pt = cls.interpolate_polyline_at(poly, cum_lengths, s_end)

        # Intermediate whole points (vectorized selection)
        inner = poly[(cum_lengths > s_start) & (cum_lengths < s_end)]

        return np.vstack([start_pt[None, :], inner, end_pt[None, :]])

    @classmethod
    def _cut_polyline_at_positions(
        cls,
        sec_poly: np.ndarray,
        cum_lengths: np.ndarray,
        cut_positions,
        cut_radius: float,
    ) -> list[np.ndarray]:
        """
        Remove a zone of +/- cut_radius (curvilinear) around every cut
        position from `sec_poly` and return the remaining sub-polylines.
        """
        total_length = cum_lengths[-1]
        cut_positions = np.unique(cut_positions)  # sorted, duplicates removed

        excluded = [
            (max(0, s - cut_radius), min(total_length, s + cut_radius))
            for s in cut_positions
        ]

        # Merge overlapping zones
        merged_excluded = []
        for start, end in excluded:
            if merged_excluded and start <= merged_excluded[-1][1]:
                merged_excluded[-1] = (merged_excluded[-1][0], max(merged_excluded[-1][1], end))
            else:
                merged_excluded.append((start, end))

        # Keep the non-excluded zones
        kept_intervals = []
        cursor = 0.0
        for excl_start, excl_end in merged_excluded:
            if cursor < excl_start:
                kept_intervals.append((cursor, excl_start))
            cursor = excl_end
        if cursor < total_length:
            kept_intervals.append((cursor, total_length))

        pieces = []
        for interval_start, interval_end in kept_intervals:
            if interval_end - interval_start < cut_radius:
                continue  # segment too short, ignore
            sub_pts = cls.sample_polyline_between(
                sec_poly, cum_lengths, interval_start, interval_end
            )
            if len(sub_pts) >= 2:
                pieces.append(sub_pts)
        return pieces

    @classmethod
    def _cut_secondary_lines(
        cls,
        infill_primary: list[np.ndarray],
        infill_secondary: list[np.ndarray],
        nozzle_diameter: float,
        neighbor_radius_extra: float | None,
    ) -> list[np.ndarray]:
        """
        Shared engine of the two cutting methods.

        neighbor_radius_extra=None  -> test every primary segment (exact, O(N*M))
        neighbor_radius_extra=value -> only test the primary segments whose
                                       midpoint is within
                                       seg_len/2 + value of the secondary
                                       segment's midpoint (KD-tree)
        """
        cut_radius = nozzle_diameter / 2.0

        # All primary segments as arrays
        q1_parts = [np.asarray(p, dtype=float)[:-1] for p in infill_primary if len(p) >= 2]
        q2_parts = [np.asarray(p, dtype=float)[1:] for p in infill_primary if len(p) >= 2]
        if not q1_parts:
            return infill_secondary
        Q1 = np.vstack(q1_parts)
        Q2 = np.vstack(q2_parts)
        n_prim = len(Q1)

        tree = None
        if neighbor_radius_extra is not None:
            tree = cKDTree(((Q1 + Q2) / 2.0)[:, :2])

        result = []

        for sec_poly in infill_secondary:
            if len(sec_poly) < 2:
                continue
            sec_poly = np.asarray(sec_poly)

            seg_lengths = np.linalg.norm(np.diff(sec_poly, axis=0), axis=1)
            cum_lengths = np.concatenate([[0], np.cumsum(seg_lengths)])
            if cum_lengths[-1] == 0:
                continue

            P1 = sec_poly[:-1].astype(float)
            P2 = sec_poly[1:].astype(float)
            n_seg = len(P1)

            # Candidate (secondary segment, primary segment) pairs
            if tree is None:
                pair_i = np.repeat(np.arange(n_seg), n_prim)
                pair_j = np.tile(np.arange(n_prim), n_seg)
            else:
                radius = seg_lengths / 2.0 + neighbor_radius_extra
                neighbors = tree.query_ball_point(((P1 + P2) / 2.0)[:, :2], r=radius)
                counts = np.fromiter((len(n) for n in neighbors), dtype=np.int64, count=n_seg)
                if counts.sum() == 0:
                    result.append(sec_poly)
                    continue
                pair_i = np.repeat(np.arange(n_seg), counts)
                pair_j = np.concatenate(
                    [np.asarray(n, dtype=np.int64) for n in neighbors if len(n)]
                )

            hit, t = cls._segment_intersections_2d(
                P1[pair_i], P2[pair_i], Q1[pair_j], Q2[pair_j]
            )
            if not hit.any():
                result.append(sec_poly)
                continue

            i_hit = pair_i[hit]
            seg_len_hit = seg_lengths[i_hit]
            # Curvilinear position of each intersection on sec_poly
            t_norm = np.clip(t[hit] * seg_len_hit / (seg_len_hit + 1e-12), 0, 1)
            cut_positions = cum_lengths[i_hit] + t_norm * seg_len_hit

            result.extend(
                cls._cut_polyline_at_positions(sec_poly, cum_lengths, cut_positions, cut_radius)
            )

        return result

    @classmethod
    def cut_infill_at_intersections(
        cls,
        infill_primary: list[np.ndarray],     # these lines stay continuous (not cut)
        infill_secondary: list[np.ndarray],   # these lines are cut at intersections
        nozzle_diameter: float = 0.70,
    ) -> list[np.ndarray]:
        """
        Cut the secondary lines at every intersection with the primary
        lines. Returns the cut secondary segments (crossing zones removed).

        The cut zone around each intersection is nozzle_diameter wide
        (half a nozzle width removed on each side).

        Exact version: tests every pair of segments (vectorized, but still
        O(N*M) - prefer cut_infill_at_intersections_fast on large layers).
        """
        return cls._cut_secondary_lines(
            infill_primary, infill_secondary, nozzle_diameter, neighbor_radius_extra=None
        )

    @classmethod
    def cut_infill_at_intersections_fast(
        cls,
        infill_primary: list[np.ndarray],
        infill_secondary: list[np.ndarray],
        nozzle_diameter: float = 0.70,
        infill_percentage: float = 20.0,
    ) -> list[np.ndarray]:
        """
        Fast version using a spatial index: instead of testing every pair,
        only test the primary segments close enough to each secondary
        segment (KD-tree on segment midpoints). The intersection tests
        themselves are vectorized per secondary polyline.
        """
        spacing = cls.infill_spacing(nozzle_diameter, infill_percentage)

        return cls._cut_secondary_lines(
            infill_primary,
            infill_secondary,
            nozzle_diameter,
            neighbor_radius_extra=spacing + nozzle_diameter,
        )

    # ------------------------------------------------------------------
    # Support printing path
    # ------------------------------------------------------------------

    @staticmethod
    def compute_max_connection_length(
        nozzle_diameter: float,
        infill_percentage: float,
        layer_height: float,
        margin: float = 1.1,
    ) -> float:
        """
        Geometrically compute max_connection_length as the diagonal between
        two adjacent lines (XY spacing, Z layer_height), with a safety
        margin.

        - 100% infill -> spacing = nozzle_diameter -> very short connections
        - 10%  infill -> large spacing -> longer connections accepted
        - layer_height bounds the vertical component
        """
        spacing = SlicedMold.infill_spacing(nozzle_diameter, infill_percentage)

        max_conn = np.sqrt(spacing**2 + layer_height**2) * margin
        print(f"Infill {infill_percentage}% -> spacing={spacing:.3f}, "
              f"max_connection_length={max_conn:.3f} mm")
        return max_conn

    @classmethod
    def collapse_infill_line(
        cls,
        points: np.ndarray,
        straight_tolerance: float = 0.05,
    ) -> np.ndarray:
        """
        Reduce an infill line to its two end points when it is a straight
        line (the normal case: infill lines are cuts of a planar layer by
        a plane x = const or y = const).

        Safety net: the line is only collapsed if it really is straight,
        i.e. every point lies within `straight_tolerance` of the chord
        between its end points AND the points progress monotonically
        along that chord (no back-and-forth). Otherwise the line is not
        a simple straight stroke (it may contain a jump or a turn): it is
        kept as a Ramer-Douglas-Peucker simplified polyline (or left
        untouched if it doubles back on itself) instead of being
        flattened - no jump is ever erased.
        """
        pts = np.asarray(points, dtype=float)
        if len(pts) <= 2:
            return pts

        a, b = pts[0], pts[-1]
        chord = b - a
        chord_len_sq = float(chord @ chord)
        if chord_len_sq < 1e-12:
            return cls.simplify_polyline(pts, straight_tolerance)

        t = (pts - a) @ chord / chord_len_sq
        dev = np.linalg.norm(pts - (a + t[:, None] * chord), axis=1)

        monotonic = np.all(np.diff(t) >= -1e-9)
        if not monotonic:
            # Back-and-forth along the line: RDP would flatten it (all the
            # points are on the chord), so keep the points untouched.
            return pts

        if dev.max() <= straight_tolerance:
            return np.array([a, b])

        return cls.simplify_polyline(pts, straight_tolerance)

    @classmethod
    def _make_crossing_blocker(cls, primary: list[np.ndarray]):
        """
        Return a callable (p_start, p_end) -> bool that is True when the
        straight move p_start -> p_end crosses (in XY) one of the primary
        lines. Such a move would be a printed connection laid across a
        primary bead, i.e. the crossing would be printed twice: it must
        be a leave/approach (travel) instead.
        """
        q1 = [np.asarray(p, dtype=float)[:-1] for p in primary if len(p) >= 2]
        q2 = [np.asarray(p, dtype=float)[1:] for p in primary if len(p) >= 2]
        if not q1:
            return None
        Q1, Q2 = np.vstack(q1), np.vstack(q2)
        n = len(Q1)

        def blocker(p_start, p_end) -> bool:
            a = np.broadcast_to(np.asarray(p_start, dtype=float), (n, 3))
            b = np.broadcast_to(np.asarray(p_end, dtype=float), (n, 3))
            hit, _ = cls._segment_intersections_2d(a, b, Q1, Q2)
            return bool(hit.any())

        return blocker

    def build_support_path(
        self,
        nozzle_diameter: float = 0.70,
        infill_percentage: float = 20.0,
        approach_distance: float = 1.0,
        layer_height: float = 0.35,
        shell_simplify_tolerance: float | None = None,
        collapse_infill: bool = False,
        infill_straight_tolerance: float = 0.05,
    ):
        """
        Build the full printing path for this support layer: contour
        shells first, then a zigzag infill where the primary direction (X
        or Y, alternating every other layer) stays continuous and the
        secondary direction is cut wherever it crosses the primary lines.

        Mold-specific simplification (applied to the curves BEFORE they
        are stitched, so every curve keeps its exact end points and the
        connections / approach / leave moves are unchanged):
        - shell_simplify_tolerance: contour shells stay sampled polylines
          but are simplified with Ramer-Douglas-Peucker (max deviation in
          mm). None = no simplification.
        - collapse_infill: infill lines are reduced to their two end
          points (see collapse_infill_line). Each cut piece of a
          secondary line stays a separate curve, so the gaps (jumps)
          between pieces are preserved.
        """
        max_connection_length = self.compute_max_connection_length(
            nozzle_diameter=nozzle_diameter,
            infill_percentage=infill_percentage,
            layer_height=layer_height,
        )

        def sort_zigzag(lines, axis):
            if not lines:
                return []
            sorted_lines = sorted(lines, key=lambda p: p[:, axis].mean())
            for i, poly in enumerate(sorted_lines):
                if i % 2 == 1:
                    sorted_lines[i] = poly[::-1]
            return sorted_lines

        # Prepare primary and secondary depending on parity
        infill_x_sorted = sort_zigzag(self.infill_x, axis=0)
        infill_y_sorted = sort_zigzag(self.infill_y, axis=1)

        if self.q % 2 == 0:
            primary, secondary_src, parity = infill_x_sorted, infill_y_sorted, "even -> X continuous, Y cut"
        else:
            primary, secondary_src, parity = infill_y_sorted, infill_x_sorted, "odd -> Y continuous, X cut"

        secondary = self.cut_infill_at_intersections_fast(
            infill_primary=primary,
            infill_secondary=secondary_src,
            nozzle_diameter=nozzle_diameter,
            infill_percentage=infill_percentage,
        )
        print(f"  Layer {self.q} ({parity})")

        active_infill = primary + secondary  # full list to print

        # Mold-specific simplification (after the cutting, which needs the
        # full-resolution primary lines)
        contour_shells = self.contour_shells
        if shell_simplify_tolerance is not None:
            contour_shells = [
                self.simplify_polyline(c, shell_simplify_tolerance)
                for c in contour_shells
            ]
        if collapse_infill:
            active_infill = [
                self.collapse_infill_line(c, infill_straight_tolerance)
                for c in active_infill
            ]
        min_len = 0.5 * nozzle_diameter

        def finalize(curves):
            if collapse_infill:
                curves = [self.collapse_infill_line(c, infill_straight_tolerance)
                          for c in curves]
            return [c for c in curves
                    if len(c) >= 2 and np.linalg.norm(c[-1] - c[0]) > min_len]

        primary_active = finalize(primary)
        active_infill = primary_active + finalize(secondary)

        # Pass 1: contour shells
        shell_segments, _, shell_types = self.build_path_single_pass(
            curves=contour_shells,
            approach_code=5,
            connection_end_code=3,
            continuation_code=2,
            approach_distance=approach_distance,
            max_connection_length=max_connection_length,
        )

        # Pass 2: infill (primary + cut secondary). A move that would cross
        # a primary line is forbidden as a connection (it would print the
        # crossing twice): it becomes a leave + approach (not printed).
        infill_segments, _, infill_types = self.build_path_single_pass(
            curves=active_infill,
            approach_code=4,
            connection_end_code=1,
            continuation_code=0,
            approach_distance=approach_distance,
            max_connection_length=max_connection_length,
            connection_blocker=self._make_crossing_blocker(primary_active),
        )

        all_segments = shell_segments + infill_segments
        all_types = shell_types + infill_types

        print(f"  primary: {len(primary)} lines")
        print(f"  secondary: {len(secondary)} lines")

        return all_segments, all_types

    # ------------------------------------------------------------------
    # Multi-layer path export (for external trajectory simulation, e.g. RoboDK)
    # ------------------------------------------------------------------

    @classmethod
    def export_layers_to_txt(
        cls,
        layers: list["SlicedMold"],
        filepath,
        nozzle_diameter: float = 0.70,
        infill_percentage: float = 20.0,
        approach_distance: float = 1.0,
        layer_height: float = 0.35,
        include_orientation: bool = False,
        approach_sign: float = -1.0,
        simplify_tolerance: float | None = None,
        shell_simplify_tolerance: float | None = None,
        collapse_infill: bool = False,
        infill_straight_tolerance: float = 0.05,
    ) -> None:
        """
        Build the full support printing path for every given layer and
        write the whole trajectory (all layers, in order) to a single
        text file, ready to be loaded by an external trajectory simulator
        such as RoboDK.

        Mold-specific simplification (recommended over simplify_tolerance):
        - shell_simplify_tolerance: RDP tolerance (mm) for the contour
          shells only (they stay polylines).
        - collapse_infill: infill lines are reduced to their two end
          points; jumps between lines / cut pieces are preserved.
        - infill_straight_tolerance: max deviation (mm) for an infill
          line to be considered straight (otherwise it is only RDP
          simplified, never flattened).

        simplify_tolerance: generic option, applied afterwards to every
        segment with Ramer-Douglas-Peucker (see
        SlicedObject.simplify_polyline). Leave it to None when using the
        mold-specific options above.
        """
        filepath = Path(filepath)

        for i, layer in enumerate(layers):
            segments, types = layer.build_support_path(
                nozzle_diameter=nozzle_diameter,
                infill_percentage=infill_percentage,
                approach_distance=approach_distance,
                layer_height=layer_height,
                shell_simplify_tolerance=shell_simplify_tolerance,
                collapse_infill=collapse_infill,
                infill_straight_tolerance=infill_straight_tolerance,
            )

            layer.export_printing_path(
                segments,
                types,
                filepath,
                include_orientation=include_orientation,
                approach_sign=approach_sign,
                simplify_tolerance=simplify_tolerance,
                layer_id=layer.q,
                mode="w" if i == 0 else "a",
            )

        print(f"Support path exported to {filepath} ({len(layers)} layers)")
